/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Home / main menu screen data
         * @description Landing data — title, available modes and the player's aggregate stats.
         */
        get: operations["getHomePage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a new interview session
         * @description Creates an interview session and returns its `interviewId` plus the
         *     candidate lineup. `context` selects mode and difficulty.
         */
        post: operations["startInterview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{interviewId}/question": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current question with candidate answers
         * @description Returns the next unanswered question for the session, its position in the
         *     run (`index` of `total`), the answer time limit, and one answer per
         *     candidate. The correct answer is **not** flagged in this response.
         */
        get: operations["getQuestion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{interviewId}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit the chosen answer for a question
         * @description Records the player's chosen answer for a question and returns immediate
         *     feedback (correct/incorrect, the correct answer id, points awarded and the
         *     running score/streak). Maps to `saveAnswer(question, answer)`.
         */
        post: operations["saveAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{interviewId}/statistic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Per-candidate selection statistics
         * @description How many times each candidate's answer was chosen across the run, plus the
         *     overall correct count. Shown before the offer screen (requirement 4).
         */
        get: operations["getInterviewStatistic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{interviewId}/offer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Make an offer to (hire) a candidate
         * @description Player chooses which candidate to hire. Maps to `offer(person)`.
         */
        post: operations["offer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{interviewId}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Final score result of the interview
         * @description The end-of-game result screen — score (correct of total), points, best
         *     streak and a per-question breakdown. Maps to `getInterviewResult(id)`.
         */
        get: operations["getInterviewResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{interviewId}/ai-result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * AI analysis and learning roadmap
         * @description AI-generated analysis of the player's decisions, the hiring verdict and a
         *     roadmap of topics to study. May be computed asynchronously — see the
         *     `status` field. Maps to `getAiiInterviewResult(id)`.
         */
        get: operations["getAiInterviewResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HomePage: {
            /** @example Tech Lead Simulator */
            title: string;
            /** @example Pass the interview and build the best team! */
            subtitle?: string;
            modes: components["schemas"]["GameMode"][];
            playerStats: components["schemas"]["PlayerStats"];
        };
        GameMode: {
            mode: components["schemas"]["Mode"];
            /** @example Classic */
            title: string;
            /** @example Full path: 10 questions. */
            description?: string;
            /** @example 10 */
            questionCount: number;
        };
        /** @description Aggregate stats shown on the home / stats screen. */
        PlayerStats: {
            /** @example 12 */
            gamesPlayed: number;
            /**
             * Format: float
             * @description Win ratio 0..1.
             * @example 0.75
             */
            winRate: number;
            /**
             * @description Best number of correct answers in a single run.
             * @example 8
             */
            bestResult?: number;
            /** @example 7 */
            candidatesHired?: number;
        };
        /**
         * @description Game mode. CLASSIC = 10 questions, HARDCORE = 20.
         * @enum {string}
         */
        Mode: "CLASSIC" | "HARDCORE";
        /** @enum {string} */
        Difficulty: "EASY" | "MEDIUM" | "HARD";
        /** @description The `context` passed to `start(context)`. */
        StartInterviewRequest: {
            mode: components["schemas"]["Mode"];
            difficulty?: components["schemas"]["Difficulty"];
            /** @example You */
            playerName?: string;
        };
        InterviewSession: {
            /**
             * Format: int64
             * @example 1001
             */
            interviewId: number;
            mode: components["schemas"]["Mode"];
            difficulty?: components["schemas"]["Difficulty"];
            /** @example 10 */
            totalQuestions: number;
            /** @description The virtual candidates taking part in this interview. */
            candidates: components["schemas"]["Candidate"][];
        };
        Candidate: {
            /** @example 2 */
            id: number;
            /** @example Alexey */
            name: string;
            /** @example Backend Developer */
            role: string;
            /**
             * Format: uri-reference
             * @example /assets/candidates/alexey.png
             */
            avatarUrl?: string;
            /**
             * @example [
             *       "Algorithms",
             *       "Databases",
             *       "Optimization"
             *     ]
             */
            strengths?: string[];
        };
        Question: {
            /** @example 3 */
            questionId: number;
            /**
             * @description 1-based position of this question in the run.
             * @example 3
             */
            index: number;
            /** @example 10 */
            total: number;
            /** @example How would you optimize a slow SQL query? */
            text: string;
            /**
             * @description Seconds allowed to answer; null means no limit.
             * @example 45
             */
            timeLimitSeconds?: number;
            /** @description One answer per candidate. Exactly one is correct (not flagged here). */
            answers: components["schemas"]["AnswerOption"][];
        };
        AnswerOption: {
            /**
             * @description Identifier of this answer option (the `answer` in saveAnswer).
             * @example 11
             */
            answerId: number;
            /**
             * @description The candidate who gave this answer.
             * @example 2
             */
            candidateId: number;
            /** @example Add indexes on the queried columns. */
            text: string;
        };
        /** @description Body of `saveAnswer(question, answer)`. */
        AnswerRequest: {
            /** @example 3 */
            questionId: number;
            /**
             * @description The answer option the player selected as correct.
             * @example 11
             */
            answerId: number;
        };
        AnswerResult: {
            /** @example true */
            correct: boolean;
            /**
             * @description The answer option that was actually correct.
             * @example 11
             */
            correctAnswerId: number;
            /** @example 10 */
            pointsAwarded: number;
            /**
             * @description Total correct answers so far in the run.
             * @example 4
             */
            correctCount: number;
            /** @example 3 */
            currentStreak: number;
            /** @example 40 */
            totalPoints?: number;
            /**
             * @description How many questions have been answered (1..total).
             * @example 3
             */
            answeredCount: number;
            /** @example 10 */
            totalQuestions: number;
            /**
             * @description True when this was the last question of the run.
             * @example false
             */
            finished?: boolean;
        };
        InterviewStatistic: {
            /** @example 10 */
            totalQuestions: number;
            /** @example 7 */
            correctCount: number;
            /** @description How many times each candidate's answer was chosen. */
            perCandidate: components["schemas"]["CandidateSelection"][];
        };
        CandidateSelection: {
            /** @example 2 */
            candidateId: number;
            /** @example Alexey */
            name: string;
            /** @example Backend Developer */
            role?: string;
            /**
             * @description How many times the player picked this candidate's answer.
             * @example 7
             */
            timesChosen: number;
        };
        /** @description Body of `offer(person)`. */
        OfferRequest: {
            /**
             * @description The candidate the player hires.
             * @example 2
             */
            personId: number;
        };
        OfferResult: {
            /**
             * Format: int64
             * @example 1001
             */
            interviewId: number;
            hiredCandidate: components["schemas"]["Candidate"];
            /** @example Alexey has joined your team! */
            message?: string;
        };
        InterviewResult: {
            /**
             * Format: int64
             * @example 1001
             */
            interviewId: number;
            /** @example 7 */
            correctCount: number;
            /** @example 10 */
            totalQuestions: number;
            /** @example 70 */
            totalPoints: number;
            /** @example 4 */
            bestStreak: number;
            /** @description Per-question outcome for the detailed statistics screen. */
            breakdown: components["schemas"]["QuestionOutcome"][];
        };
        QuestionOutcome: {
            /** @example 1 */
            questionId: number;
            /** @example What is SOLID? */
            text: string;
            /** @example true */
            correct: boolean;
        };
        AiInterviewResult: {
            /**
             * Format: int64
             * @example 1001
             */
            interviewId: number;
            /**
             * @description PENDING while the analysis is still being generated (HTTP 202).
             * @example READY
             * @enum {string}
             */
            status: "READY" | "PENDING";
            /**
             * @description Human-readable analysis of the player's hiring decisions.
             * @example You favored strong database answers but missed some architecture trade-offs.
             */
            summary?: string;
            /**
             * @description Whether hiring the chosen candidate was a good call.
             * @example Good hire — Alexey fits the backend-heavy roadmap.
             */
            verdict?: string;
            /** @example 2 */
            hiredCandidateId?: number;
            /** @description Topics the player should study, with resources. */
            roadmap?: components["schemas"]["RoadmapItem"][];
        };
        RoadmapItem: {
            /** @example Database indexing strategies */
            topic: string;
            /** @example You missed 2 questions on query optimization. */
            reason?: string;
            /**
             * @example HIGH
             * @enum {string}
             */
            priority?: "LOW" | "MEDIUM" | "HIGH";
            resources?: components["schemas"]["Resource"][];
        };
        Resource: {
            /** @example Use The Index, Luke! */
            title: string;
            /**
             * Format: uri
             * @example https://use-the-index-luke.com/
             */
            url?: string;
        };
        Error: {
            /** @example INTERVIEW_NOT_FOUND */
            code: string;
            /** @example No interview session with id 1001. */
            message: string;
            /** Format: date-time */
            timestamp?: string;
        };
    };
    responses: {
        /** @description Malformed or invalid request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Interview session or referenced entity not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Interview session identifier returned by `POST /interviews`. */
        InterviewId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHomePage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Home page payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomePage"];
                };
            };
        };
    };
    startInterview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartInterviewRequest"];
            };
        };
        responses: {
            /** @description Interview session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewSession"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Interview session identifier returned by `POST /interviews`. */
                interviewId: components["parameters"]["InterviewId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current question */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description No question available — all rounds already answered. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    saveAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Interview session identifier returned by `POST /interviews`. */
                interviewId: components["parameters"]["InterviewId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description Answer recorded, feedback returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Question already answered. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getInterviewStatistic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Interview session identifier returned by `POST /interviews`. */
                interviewId: components["parameters"]["InterviewId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Interview statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewStatistic"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    offer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Interview session identifier returned by `POST /interviews`. */
                interviewId: components["parameters"]["InterviewId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferRequest"];
            };
        };
        responses: {
            /** @description Offer recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getInterviewResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Interview session identifier returned by `POST /interviews`. */
                interviewId: components["parameters"]["InterviewId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Interview result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewResult"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getAiInterviewResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Interview session identifier returned by `POST /interviews`. */
                interviewId: components["parameters"]["InterviewId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AI result (ready) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiInterviewResult"];
                };
            };
            /** @description AI result is still being generated — retry later. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiInterviewResult"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
