create table candidate (
    id         bigint generated by default as identity primary key,
    name       varchar(100) not null,
    role       varchar(100) not null,
    avatar_url varchar(255),
    slot       int not null unique
);

create table candidate_strength (
    candidate_id bigint not null references candidate (id),
    strength     varchar(100) not null
);

create table question_template (
    id                 bigint generated by default as identity primary key,
    text               varchar(500) not null,
    topic              varchar(100) not null,
    difficulty         varchar(20)  not null,
    time_limit_seconds int
);

create table answer_template (
    id             bigint generated by default as identity primary key,
    question_id    bigint       not null references question_template (id),
    candidate_slot int          not null,
    text           varchar(500) not null,
    is_correct     boolean      not null default false
);

create table interview (
    id                 bigint generated by default as identity primary key,
    mode               varchar(20) not null,
    difficulty         varchar(20),
    player_name        varchar(100),
    status             varchar(20) not null,
    total_questions    int         not null,
    hired_candidate_id bigint references candidate (id),
    created_at         timestamp   not null
);

create table interview_round (
    id               bigint generated by default as identity primary key,
    interview_id     bigint  not null references interview (id),
    question_id      bigint  not null references question_template (id),
    round_index      int     not null,
    chosen_answer_id bigint,
    correct          boolean,
    points_awarded   int     not null default 0,
    answered         boolean not null default false
);

create index idx_round_interview on interview_round (interview_id);
create index idx_answer_question on answer_template (question_id);
