-- Translate the seeded interview content (questions + answers) to Russian.
-- Topics and candidate strengths stay in English: they are matching keys used by
-- RuleBasedAiAnalyzer, not display-only text.

update question_template set text = 'Как бы вы ускорили медленный SQL-запрос?'                     where id = 1;
update question_template set text = 'Что обычно автоматизирует CI-пайплайн?'                      where id = 2;
update question_template set text = 'Какова сложность бинарного поиска по времени?'               where id = 3;
update question_template set text = 'Как сделать веб-страницу доступной для скринридеров?'        where id = 4;
update question_template set text = 'Когда стоит добавлять индекс в базу данных?'                 where id = 5;
update question_template set text = 'Какую проблему решает Docker?'                               where id = 6;
update question_template set text = 'Как обнаружить узкое место со сложностью O(n^2)?'            where id = 7;
update question_template set text = 'Что такое переменная?'                                       where id = 8;
update question_template set text = 'Что такое транзакция в базе данных?'                         where id = 9;
update question_template set text = 'Зачем нужен обратный прокси (reverse proxy)?'                where id = 10;
update question_template set text = 'Что такое нормализация в базах данных?'                      where id = 11;
update question_template set text = 'Как работает специфичность в CSS?'                           where id = 12;
update question_template set text = 'Как бы вы устранили проблему N+1 запросов?'                  where id = 13;
update question_template set text = 'Что такое blue-green deployment?'                            where id = 14;
update question_template set text = 'В чём разница между стеком и очередью?'                      where id = 15;
update question_template set text = 'Что такое семантическая вёрстка (semantic HTML)?'            where id = 16;
update question_template set text = 'Как выбрать между хеш-таблицей и деревом поиска?'            where id = 17;
update question_template set text = 'Что делает балансировщик нагрузки?'                          where id = 18;
update question_template set text = 'Когда денормализация оправдана?'                             where id = 19;
update question_template set text = 'Что такое progressive enhancement?'                          where id = 20;

update answer_template set text = 'Добавить индекс на фильтруемые колонки и посмотреть план запроса.'      where id = 1;
update answer_template set text = 'Увеличить размер шрифта.'                                              where id = 2;
update answer_template set text = 'Перезапустить сервер базы данных.'                                     where id = 3;
update answer_template set text = 'Удалить случайные строки.'                                             where id = 4;
update answer_template set text = 'Он рендерит CSS.'                                                      where id = 5;
update answer_template set text = 'Он рисует логотип.'                                                    where id = 6;
update answer_template set text = 'Он автоматически собирает, тестирует и деплоит код.'                    where id = 7;
update answer_template set text = 'Он пишет требования.'                                                  where id = 8;
update answer_template set text = 'O(log n).'                                                             where id = 9;
update answer_template set text = 'O(n log n).'                                                           where id = 10;
update answer_template set text = 'O(n).'                                                                 where id = 11;
update answer_template set text = 'Всегда O(1).'                                                          where id = 12;
update answer_template set text = 'Использовать картинки поменьше.'                                       where id = 13;
update answer_template set text = 'Добавить ARIA-роли и семантические элементы с alt-текстом.'            where id = 14;
update answer_template set text = 'Отключить JavaScript.'                                                 where id = 15;
update answer_template set text = 'Ничего особенного делать не нужно.'                                    where id = 16;
update answer_template set text = 'Когда по колонке часто фильтруют или джойнят.'                          where id = 17;
update answer_template set text = 'Всегда и на каждую колонку.'                                           where id = 18;
update answer_template set text = 'Никогда, индексы тормозят.'                                            where id = 19;
update answer_template set text = 'Когда таблица пустая.'                                                 where id = 20;
update answer_template set text = 'Он компилирует Java.'                                                  where id = 21;
update answer_template set text = 'Он стилизует интерфейс.'                                               where id = 22;
update answer_template set text = 'Он упаковывает приложение с зависимостями в переносимый образ.'        where id = 23;
update answer_template set text = 'Он заменяет базу данных.'                                              where id = 24;
update answer_template set text = 'Профилировать код и искать вложенные циклы по входным данным.'         where id = 25;
update answer_template set text = 'Добавить ещё CSS.'                                                     where id = 26;
update answer_template set text = 'Перезагрузить машину.'                                                 where id = 27;
update answer_template set text = 'Угадать наугад.'                                                       where id = 28;
update answer_template set text = 'Именованная область памяти для значения.'                              where id = 29;
update answer_template set text = 'Разновидность цикла.'                                                  where id = 30;
update answer_template set text = 'Сетевой протокол.'                                                     where id = 31;
update answer_template set text = 'Именованная область памяти для значения.'                              where id = 32;
update answer_template set text = 'Единица работы по принципу «всё или ничего» (атомарность).'            where id = 33;
update answer_template set text = 'Правило CSS.'                                                          where id = 34;
update answer_template set text = 'Образ контейнера.'                                                     where id = 35;
update answer_template set text = 'Разновидность кнопки.'                                                 where id = 36;
update answer_template set text = 'Чтобы хранить данные.'                                                 where id = 37;
update answer_template set text = 'Чтобы стилизовать страницы.'                                           where id = 38;
update answer_template set text = 'Чтобы маршрутизировать и прикрыть бэкенд-сервисы одной точкой входа.'  where id = 39;
update answer_template set text = 'Чтобы компилировать код.'                                              where id = 40;
update answer_template set text = 'Организация таблиц так, чтобы снизить избыточность данных.'            where id = 41;
update answer_template set text = 'Перевод текста в верхний регистр.'                                     where id = 42;
update answer_template set text = 'Масштабирование серверов.'                                             where id = 43;
update answer_template set text = 'Ручное удаление дубликатов.'                                           where id = 44;
update answer_template set text = 'Специфичность определяется случайно.'                                  where id = 45;
update answer_template set text = 'Селекторы оцениваются в баллах: более специфичный побеждает.'          where id = 46;
update answer_template set text = 'Работают только инлайновые стили.'                                     where id = 47;
update answer_template set text = 'В CSS нет специфичности.'                                              where id = 48;
update answer_template set text = 'Собрать дочерние выборки в один запрос (join или IN).'                 where id = 49;
update answer_template set text = 'Добавить спиннер.'                                                     where id = 50;
update answer_template set text = 'Увеличить таймаут.'                                                    where id = 51;
update answer_template set text = 'Не обращать внимания.'                                                 where id = 52;
update answer_template set text = 'Алгоритм сортировки.'                                                  where id = 53;
update answer_template set text = 'CSS-фреймворк.'                                                        where id = 54;
update answer_template set text = 'Развернуть параллельное окружение и переключить на него трафик.'       where id = 55;
update answer_template set text = 'Индекс в базе данных.'                                                 where id = 56;
update answer_template set text = 'Стек — LIFO, очередь — FIFO.'                                          where id = 57;
update answer_template set text = 'Это одно и то же.'                                                     where id = 58;
update answer_template set text = 'Стек — FIFO, очередь — LIFO.'                                          where id = 59;
update answer_template set text = 'Обе структуры дают произвольный доступ.'                               where id = 60;
update answer_template set text = 'Использовать div для всего подряд.'                                    where id = 61;
update answer_template set text = 'Использовать теги, описывающие смысл (nav, article, header).'          where id = 62;
update answer_template set text = 'Прописывать все стили инлайн.'                                         where id = 63;
update answer_template set text = 'Полностью отказаться от HTML.'                                         where id = 64;
update answer_template set text = 'Хеш-таблица — доступ за O(1), дерево — когда нужен порядок ключей.'    where id = 65;
update answer_template set text = 'Всегда использовать дерево.'                                           where id = 66;
update answer_template set text = 'Это одно и то же.'                                                     where id = 67;
update answer_template set text = 'Не использовать словари вообще.'                                       where id = 68;
update answer_template set text = 'Он хранит файлы.'                                                      where id = 69;
update answer_template set text = 'Он рендерит HTML.'                                                     where id = 70;
update answer_template set text = 'Он распределяет трафик между несколькими инстансами.'                  where id = 71;
update answer_template set text = 'Он компилирует код.'                                                   where id = 72;
update answer_template set text = 'Когда выигрыш в скорости чтения важнее издержек на избыточность.'      where id = 73;
update answer_template set text = 'Денормализовать всегда.'                                               where id = 74;
update answer_template set text = 'Не денормализовать никогда.'                                           where id = 75;
update answer_template set text = 'Только по воскресеньям.'                                               where id = 76;
update answer_template set text = 'Отключать сайт для старых браузеров.'                                  where id = 77;
update answer_template set text = 'Начинать с рабочего базового варианта и наслаивать возможности.'       where id = 78;
update answer_template set text = 'Отдавать только картинки.'                                             where id = 79;
update answer_template set text = 'Требовать самый свежий браузер.'                                       where id = 80;
